
services:
  web:
    image: php:8.0-apache
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=password
      - MYSQL_DB=PracticaWebApp

    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"
    networks:
      - app-network
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=PracticaWebApp
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge